#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-pdfbox
Version  : 2.0.4
Release  : 2
URL      : https://repo1.maven.org/maven2/org/apache/pdfbox/fontbox/2.0.4/fontbox-2.0.4.jar
Source0  : https://repo1.maven.org/maven2/org/apache/pdfbox/fontbox/2.0.4/fontbox-2.0.4.jar
Source1  : https://repo1.maven.org/maven2/org/apache/pdfbox/fontbox/2.0.4/fontbox-2.0.4.pom
Source2  : https://repo1.maven.org/maven2/org/apache/pdfbox/pdfbox-parent/2.0.4/pdfbox-parent-2.0.4.pom
Source3  : https://repo1.maven.org/maven2/org/apache/pdfbox/pdfbox/2.0.4/pdfbox-2.0.4.jar
Source4  : https://repo1.maven.org/maven2/org/apache/pdfbox/pdfbox/2.0.4/pdfbox-2.0.4.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-pdfbox-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-pdfbox package.
Group: Data

%description data
data components for the mvn-pdfbox package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/pdfbox/fontbox/2.0.4
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/pdfbox/fontbox/2.0.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/pdfbox/fontbox/2.0.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/pdfbox/fontbox/2.0.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/pdfbox/pdfbox-parent/2.0.4
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/pdfbox/pdfbox-parent/2.0.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/pdfbox/pdfbox/2.0.4
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/pdfbox/pdfbox/2.0.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/pdfbox/pdfbox/2.0.4
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/pdfbox/pdfbox/2.0.4


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/pdfbox/fontbox/2.0.4/fontbox-2.0.4.jar
/usr/share/java/.m2/repository/org/apache/pdfbox/fontbox/2.0.4/fontbox-2.0.4.pom
/usr/share/java/.m2/repository/org/apache/pdfbox/pdfbox-parent/2.0.4/pdfbox-parent-2.0.4.pom
/usr/share/java/.m2/repository/org/apache/pdfbox/pdfbox/2.0.4/pdfbox-2.0.4.jar
/usr/share/java/.m2/repository/org/apache/pdfbox/pdfbox/2.0.4/pdfbox-2.0.4.pom
